# Generated by Django 4.2.3 on 2023-08-02 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_comment_options_post_likes_short_savedposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedposts',
            options={'verbose_name': 'Сохраненные видео', 'verbose_name_plural': 'Сохраненные видео'},
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='posts',
            field=models.ManyToManyField(related_name='saved_posts', to='core.post', verbose_name='Saved Post'),
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
