# Generated by Django 4.2.3 on 2023-08-03 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_savedposts_options_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short',
            new_name='Shorts',
        ),
    ]
