# Generated by Django 4.2.3 on 2023-08-08 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_short_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedposts',
            options={'verbose_name': 'Сохраненный пост', 'verbose_name_plural': 'Сохраненные посты'},
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='post',
            field=models.ManyToManyField(related_name='saved_posts', to='core.post', verbose_name='Сохраненные посты'),
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
